# Generated by Django 2.0.6 on 2018-09-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('type', models.BooleanField(default=False)),
                ('question', models.CharField(default='', max_length=512)),
                ('name', models.CharField(max_length=32)),
                ('item_type', models.CharField(max_length=32)),
                ('item_base_count', models.IntegerField()),
            ],
        ),
    ]
