# Generated by Django 2.0.6 on 2018-09-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=30)),
                ('nickname', models.CharField(max_length=64)),
                ('isBan', models.BooleanField(default=False)),
                ('level', models.IntegerField(default=0)),
                ('history_items', models.TextField()),
                ('img', models.CharField(max_length=128)),
                ('daily_sign', models.BooleanField(default=False)),
                ('weekly_sign', models.IntegerField(default=0)),
                ('sign_count', models.IntegerField(default=0)),
            ],
        ),
    ]
